#project
language: python 
python: 
- "3.6"

#dependecies
install:
- pip install -r flask-api/requirements.txt

#scripts
script:
  py.test --cov=app flask-api/tests/test.py

after_success:
  coveralls

